### ISSUE TITLE
Deadlock In ImageMagick Rasterization

### ISSUE THREAD

**Issue by ghost** [appditto/natricon#2]
**Describe the bug**
Natricons don't load if there are more than 2 request on the page

**Expected behavior**
Natricons would not time out and would be shown

**Additional context**
You can check out the bug on my website: https://nanojackpot.xyz icons should be displayed next to the addresses, but they aren't.

**Comment by bbedward** [comment]
There's a deadlock error with rasterized images (png/webp) that occurs every so often. That's what you're experiencing.

If you could use svg instead of png as a temporary workaround that would resolve it for now.

We're hesitant to resolve bugs until nano build off voting is over (due to their rules)

**Comment by bbedward** [comment]
Related issue is here https://github.com/gographics/imagick/issues/96 , seems like creating the magickwand once instead of for each request is the solution.
